# -*- coding: utf-8 -*-
"""util.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OKKcr_pdgGWKF8I_-cOScDokO4E74ah2
"""

from __future__ import division

import torch 
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable
import numpy as np
import cv2

def predict_transform(prediction, inp_dim, anchors, num_classes, CUDA = True):
  """
  prediction: our ouput
  inp_dim: input image dimension

  Purpose: Takes an detection feature map and turns it into 2D Tensor
  """